#!/bin/bash

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

#Color Catppuccin:
Rosewater=0xfff4dbd6
Flamingo=0xfff0c6c6
Pink=0xfff5bde6
Mauve=0xffc6a0f6
Red=0xffed8796
Maroon=0xffee99a0
Peach=0xfff5a97f
Yellow=0xffeed49f
Green=0xffa6da95
Teal=0xff8bd5ca
Sky=0xff91d7e3
Sapphire=0xff7dc4e4
Blue=0xff8aadf4
Lavender=0xffb7bdf8
Text=0xffcad3f5
Subtext1=0xffb8c0e0
Subtext0=0xffa5adcb
Overlay2=0xff939ab7
Overlay1=0xff8087a2
Overlay0=0xff6e738d
Surface2=0xff5b6078
Surface1=0xff494d64
Surface0=0xff363a4f
Base=0xff24273a
Mantle=0xff1e2030
Crust=0xff181926




PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

# Items
## - Left items.
source $"$ITEM_DIR/front_app.sh"
source $"$ITEM_DIR/space.sh"

## - Right items. source $"$ITEM_DIR/bar.sh"
source $"$ITEM_DIR/default.sh"
source $"$ITEM_DIR/clock.sh"
source $"$ITEM_DIR/volume.sh"
source $"$ITEM_DIR/battery.sh"
source $"$ITEM_DIR/welcome.sh"

## - Center items.
source $"$ITEM_DIR/media.sh"






##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
