# import themes.
#import = ["~/.config/alacritty/dracula.toml"]
import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

#window
[window]
opacity = 1
blur = true
title = "Terry Terminal"
decorations_theme_variant = "Dark"
option_as_alt = "Both"
startup_mode = "Maximized"

[font]
size = 13

[font.normal]
family = "MesloLGS NF"

[scrolling]
history = 10000


[keyboard]
bindings = [{key="Space", mods = "Command|Shift", action = "ToggleViMode"}]
